name: Build Python Package

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tool
        run: pip install build

      - name: Build the package
        run: python -m build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-dist
          path: dist/
